#ifndef __CHEBY__SFP_REGS__H__
#define __CHEBY__SFP_REGS__H__

#define SFP_REGS_SIZE 20 /* 0x14 */

/* REG stat */
#define SFP_REGS_STAT 0x0UL
#define SFP_REGS_STAT_LN0_SIGNAL_DETECT 0x1UL
#define SFP_REGS_STAT_LN0_SIGNAL_DETECT_MASK 0x1UL
#define SFP_REGS_STAT_LN0_SIGNAL_DETECT_SHIFT 0
#define SFP_REGS_STAT_LN0_RX_CDR_LOCK 0x2UL
#define SFP_REGS_STAT_LN0_RX_CDR_LOCK_MASK 0x2UL
#define SFP_REGS_STAT_LN0_RX_CDR_LOCK_SHIFT 1
#define SFP_REGS_STAT_LN0_K_LOCK 0x4UL
#define SFP_REGS_STAT_LN0_K_LOCK_MASK 0x4UL
#define SFP_REGS_STAT_LN0_K_LOCK_SHIFT 2
#define SFP_REGS_STAT_LN0_WORD_ALIGN_LINK 0x8UL
#define SFP_REGS_STAT_LN0_WORD_ALIGN_LINK_MASK 0x8UL
#define SFP_REGS_STAT_LN0_WORD_ALIGN_LINK_SHIFT 3
#define SFP_REGS_STAT_LN0_PLL_LOCK 0x10UL
#define SFP_REGS_STAT_LN0_PLL_LOCK_MASK 0x10UL
#define SFP_REGS_STAT_LN0_PLL_LOCK_SHIFT 4
#define SFP_REGS_STAT_LN0_READY 0x20UL
#define SFP_REGS_STAT_LN0_READY_MASK 0x20UL
#define SFP_REGS_STAT_LN0_READY_SHIFT 5
#define SFP_REGS_STAT_LN0_PRBS_LOCK 0x40UL
#define SFP_REGS_STAT_LN0_PRBS_LOCK_MASK 0x40UL
#define SFP_REGS_STAT_LN0_PRBS_LOCK_SHIFT 6
#define SFP_REGS_STAT_LN0_RX_VALID 0x80UL
#define SFP_REGS_STAT_LN0_RX_VALID_MASK 0x80UL
#define SFP_REGS_STAT_LN0_RX_VALID_SHIFT 7
#define SFP_REGS_STAT_LN0_RX_FIFO_EMPTY 0x100UL
#define SFP_REGS_STAT_LN0_RX_FIFO_EMPTY_MASK 0x100UL
#define SFP_REGS_STAT_LN0_RX_FIFO_EMPTY_SHIFT 8
#define SFP_REGS_STAT_LN0_TX_FIFO_AFULL 0x200UL
#define SFP_REGS_STAT_LN0_TX_FIFO_AFULL_MASK 0x200UL
#define SFP_REGS_STAT_LN0_TX_FIFO_AFULL_SHIFT 9
#define SFP_REGS_STAT_LN0_TX_FIFO_FULL 0x400UL
#define SFP_REGS_STAT_LN0_TX_FIFO_FULL_MASK 0x400UL
#define SFP_REGS_STAT_LN0_TX_FIFO_FULL_SHIFT 10
#define SFP_REGS_STAT_LN1_SIGNAL_DETECT 0x10000UL
#define SFP_REGS_STAT_LN1_SIGNAL_DETECT_MASK 0x10000UL
#define SFP_REGS_STAT_LN1_SIGNAL_DETECT_SHIFT 16
#define SFP_REGS_STAT_LN1_RX_CDR_LOCK 0x20000UL
#define SFP_REGS_STAT_LN1_RX_CDR_LOCK_MASK 0x20000UL
#define SFP_REGS_STAT_LN1_RX_CDR_LOCK_SHIFT 17
#define SFP_REGS_STAT_LN1_K_LOCK 0x40000UL
#define SFP_REGS_STAT_LN1_K_LOCK_MASK 0x40000UL
#define SFP_REGS_STAT_LN1_K_LOCK_SHIFT 18
#define SFP_REGS_STAT_LN1_WORD_ALIGN_LINK 0x80000UL
#define SFP_REGS_STAT_LN1_WORD_ALIGN_LINK_MASK 0x80000UL
#define SFP_REGS_STAT_LN1_WORD_ALIGN_LINK_SHIFT 19
#define SFP_REGS_STAT_LN1_PLL_LOCK 0x100000UL
#define SFP_REGS_STAT_LN1_PLL_LOCK_MASK 0x100000UL
#define SFP_REGS_STAT_LN1_PLL_LOCK_SHIFT 20
#define SFP_REGS_STAT_LN1_READY 0x200000UL
#define SFP_REGS_STAT_LN1_READY_MASK 0x200000UL
#define SFP_REGS_STAT_LN1_READY_SHIFT 21
#define SFP_REGS_STAT_LN1_PRBS_LOCK 0x400000UL
#define SFP_REGS_STAT_LN1_PRBS_LOCK_MASK 0x400000UL
#define SFP_REGS_STAT_LN1_PRBS_LOCK_SHIFT 22
#define SFP_REGS_STAT_LN1_RX_VALID 0x800000UL
#define SFP_REGS_STAT_LN1_RX_VALID_MASK 0x800000UL
#define SFP_REGS_STAT_LN1_RX_VALID_SHIFT 23
#define SFP_REGS_STAT_LN1_RX_FIFO_EMPTY 0x1000000UL
#define SFP_REGS_STAT_LN1_RX_FIFO_EMPTY_MASK 0x1000000UL
#define SFP_REGS_STAT_LN1_RX_FIFO_EMPTY_SHIFT 24
#define SFP_REGS_STAT_LN1_TX_FIFO_AFULL 0x2000000UL
#define SFP_REGS_STAT_LN1_TX_FIFO_AFULL_MASK 0x2000000UL
#define SFP_REGS_STAT_LN1_TX_FIFO_AFULL_SHIFT 25
#define SFP_REGS_STAT_LN1_TX_FIFO_FULL 0x4000000UL
#define SFP_REGS_STAT_LN1_TX_FIFO_FULL_MASK 0x4000000UL
#define SFP_REGS_STAT_LN1_TX_FIFO_FULL_SHIFT 26

/* REG ln0_rx_snap */
#define SFP_REGS_LN0_RX_SNAP 0x4UL

/* REG ln1_rx_snap */
#define SFP_REGS_LN1_RX_SNAP 0x8UL

/* REG ctrl */
#define SFP_REGS_CTRL 0xcUL
#define SFP_REGS_CTRL_TX_MODE 0x1UL
#define SFP_REGS_CTRL_TX_MODE_MASK 0x1UL
#define SFP_REGS_CTRL_TX_MODE_SHIFT 0

/* REG tx_pattern */
#define SFP_REGS_TX_PATTERN 0x10UL

#ifndef __ASSEMBLER__
struct sfp_regs {
  /* [0x0]: REG (ro) */
  uint32_t stat;

  /* [0x4]: REG (ro) */
  uint32_t ln0_rx_snap;

  /* [0x8]: REG (ro) */
  uint32_t ln1_rx_snap;

  /* [0xc]: REG (rw) */
  uint32_t ctrl;

  /* [0x10]: REG (rw) */
  uint32_t tx_pattern;
};
#endif /* !__ASSEMBLER__*/

#endif /* __CHEBY__SFP_REGS__H__ */
