-d /home/akiel/trunk/pub/mega_138k_test/impl/gwsynthesis/mega_138k_test.vg
-p GW5AST-138B-FCPBGA676A-2
-pn GW5AST-LV138FPG676AC2/I1
-cst /home/akiel/trunk/pub/mega_138k_test/src/pins.cst
-cfg /home/akiel/trunk/pub/mega_138k_test/impl/pnr/device.cfg
-sdc /home/akiel/trunk/pub/mega_138k_test/src/mega_60k_test.sdc
-bit
-tr
-ph
-o
-timing
-ireg_not_in_iob
-oreg_not_in_iob
-ioreg_not_in_iob
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 3
-route_option 2
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
-csr /home/akiel/trunk/pub/mega_138k_test/src/serdes/serdes.csr
