// Do not edit.  Generated by cheby 1.7.dev0 using these options:
//  --hdl verilog --gen-hdl src/sfp_regs.v --input sfp_regs.yaml
// Generated on Mon Mar 09 13:48:17 2026 by akiel



module sfp_regs
  (
    input   wire pclk,
    input   wire presetn,
    input   wire [4:2] paddr,
    input   wire psel,
    input   wire pwrite,
    input   wire penable,
    output  wire pready,
    input   wire [31:0] pwdata,
    input   wire [3:0] pstrb,
    output  wire [31:0] prdata,
    output  wire pslverr,

    // REG stat
    input   wire stat_ln0_signal_detect_i,
    input   wire stat_ln0_rx_cdr_lock_i,
    input   wire stat_ln0_k_lock_i,
    input   wire stat_ln0_word_align_link_i,
    input   wire stat_ln0_pll_lock_i,
    input   wire stat_ln0_ready_i,
    input   wire stat_ln0_prbs_lock_i,
    input   wire stat_ln0_rx_valid_i,
    input   wire stat_ln0_rx_fifo_empty_i,
    input   wire stat_ln0_tx_fifo_afull_i,
    input   wire stat_ln0_tx_fifo_full_i,
    input   wire stat_ln1_signal_detect_i,
    input   wire stat_ln1_rx_cdr_lock_i,
    input   wire stat_ln1_k_lock_i,
    input   wire stat_ln1_word_align_link_i,
    input   wire stat_ln1_pll_lock_i,
    input   wire stat_ln1_ready_i,
    input   wire stat_ln1_prbs_lock_i,
    input   wire stat_ln1_rx_valid_i,
    input   wire stat_ln1_rx_fifo_empty_i,
    input   wire stat_ln1_tx_fifo_afull_i,
    input   wire stat_ln1_tx_fifo_full_i,

    // REG ln0_rx_snap
    input   wire [31:0] ln0_rx_snap_i,

    // REG ln1_rx_snap
    input   wire [31:0] ln1_rx_snap_i,

    // REG ctrl
    output  wire ctrl_tx_mode_o,

    // REG tx_pattern
    output  wire [31:0] tx_pattern_o
  );
  wire wr_req;
  wire [4:2] wr_addr;
  wire [31:0] wr_data;
  wire rd_req;
  wire [4:2] rd_addr;
  reg [31:0] rd_data;
  reg wr_ack;
  reg rd_ack;
  reg ctrl_tx_mode_reg;
  reg ctrl_wreq;
  wire ctrl_wack;
  reg [31:0] tx_pattern_reg;
  reg tx_pattern_wreq;
  wire tx_pattern_wack;
  reg rd_ack_d0;
  reg [31:0] rd_dat_d0;
  reg wr_req_d0;
  reg [4:2] wr_adr_d0;
  reg [31:0] wr_dat_d0;

  // Write Channel
  assign wr_req = (psel & pwrite) & ~penable;
  assign wr_addr = paddr;
  assign wr_data = pwdata;
  always @(pstrb)
  ;

  // Read Channel
  assign rd_req = (psel & ~pwrite) & ~penable;
  assign rd_addr = paddr;
  assign prdata = rd_data;
  assign pready = wr_ack | rd_ack;
  assign pslverr = 1'b0;

  // pipelining for wr-in+rd-out
  always @(posedge(pclk))
  begin
    if (!presetn)
      begin
        rd_ack <= 1'b0;
        rd_data <= 32'b00000000000000000000000000000000;
        wr_req_d0 <= 1'b0;
        wr_adr_d0 <= 3'b000;
        wr_dat_d0 <= 32'b00000000000000000000000000000000;
      end
    else
      begin
        rd_ack <= rd_ack_d0;
        rd_data <= rd_dat_d0;
        wr_req_d0 <= wr_req;
        wr_adr_d0 <= wr_addr;
        wr_dat_d0 <= wr_data;
      end
  end

  // Register stat

  // Register ln0_rx_snap

  // Register ln1_rx_snap

  // Register ctrl
  assign ctrl_tx_mode_o = ctrl_tx_mode_reg;
  assign ctrl_wack = ctrl_wreq;
  always @(posedge(pclk))
  begin
    if (!presetn)
      ctrl_tx_mode_reg <= 1'b0;
    else
      if (ctrl_wreq == 1'b1)
        ctrl_tx_mode_reg <= wr_dat_d0[0];
  end

  // Register tx_pattern
  assign tx_pattern_o = tx_pattern_reg;
  assign tx_pattern_wack = tx_pattern_wreq;
  always @(posedge(pclk))
  begin
    if (!presetn)
      tx_pattern_reg <= 32'b00000000000000000000000000000000;
    else
      if (tx_pattern_wreq == 1'b1)
        tx_pattern_reg <= wr_dat_d0;
  end

  // Process for write requests.
  always @(wr_adr_d0, wr_req_d0, ctrl_wack, tx_pattern_wack)
  begin
    ctrl_wreq = 1'b0;
    tx_pattern_wreq = 1'b0;
    case (wr_adr_d0[4:2])
    3'b000:
      // Reg stat
      wr_ack = wr_req_d0;
    3'b001:
      // Reg ln0_rx_snap
      wr_ack = wr_req_d0;
    3'b010:
      // Reg ln1_rx_snap
      wr_ack = wr_req_d0;
    3'b011:
      begin
        // Reg ctrl
        ctrl_wreq = wr_req_d0;
        wr_ack = ctrl_wack;
      end
    3'b100:
      begin
        // Reg tx_pattern
        tx_pattern_wreq = wr_req_d0;
        wr_ack = tx_pattern_wack;
      end
    default:
      wr_ack = wr_req_d0;
    endcase
  end

  // Process for read requests.
  always @(rd_addr, rd_req, stat_ln0_signal_detect_i, stat_ln0_rx_cdr_lock_i, stat_ln0_k_lock_i, stat_ln0_word_align_link_i, stat_ln0_pll_lock_i, stat_ln0_ready_i, stat_ln0_prbs_lock_i, stat_ln0_rx_valid_i, stat_ln0_rx_fifo_empty_i, stat_ln0_tx_fifo_afull_i, stat_ln0_tx_fifo_full_i, stat_ln1_signal_detect_i, stat_ln1_rx_cdr_lock_i, stat_ln1_k_lock_i, stat_ln1_word_align_link_i, stat_ln1_pll_lock_i, stat_ln1_ready_i, stat_ln1_prbs_lock_i, stat_ln1_rx_valid_i, stat_ln1_rx_fifo_empty_i, stat_ln1_tx_fifo_afull_i, stat_ln1_tx_fifo_full_i, ln0_rx_snap_i, ln1_rx_snap_i, ctrl_tx_mode_reg, tx_pattern_reg)
  begin
    // By default ack read requests
    rd_dat_d0 = {32{1'bx}};
    case (rd_addr[4:2])
    3'b000:
      begin
        // Reg stat
        rd_ack_d0 = rd_req;
        rd_dat_d0[0] = stat_ln0_signal_detect_i;
        rd_dat_d0[1] = stat_ln0_rx_cdr_lock_i;
        rd_dat_d0[2] = stat_ln0_k_lock_i;
        rd_dat_d0[3] = stat_ln0_word_align_link_i;
        rd_dat_d0[4] = stat_ln0_pll_lock_i;
        rd_dat_d0[5] = stat_ln0_ready_i;
        rd_dat_d0[6] = stat_ln0_prbs_lock_i;
        rd_dat_d0[7] = stat_ln0_rx_valid_i;
        rd_dat_d0[8] = stat_ln0_rx_fifo_empty_i;
        rd_dat_d0[9] = stat_ln0_tx_fifo_afull_i;
        rd_dat_d0[10] = stat_ln0_tx_fifo_full_i;
        rd_dat_d0[15:11] = 5'b0;
        rd_dat_d0[16] = stat_ln1_signal_detect_i;
        rd_dat_d0[17] = stat_ln1_rx_cdr_lock_i;
        rd_dat_d0[18] = stat_ln1_k_lock_i;
        rd_dat_d0[19] = stat_ln1_word_align_link_i;
        rd_dat_d0[20] = stat_ln1_pll_lock_i;
        rd_dat_d0[21] = stat_ln1_ready_i;
        rd_dat_d0[22] = stat_ln1_prbs_lock_i;
        rd_dat_d0[23] = stat_ln1_rx_valid_i;
        rd_dat_d0[24] = stat_ln1_rx_fifo_empty_i;
        rd_dat_d0[25] = stat_ln1_tx_fifo_afull_i;
        rd_dat_d0[26] = stat_ln1_tx_fifo_full_i;
        rd_dat_d0[31:27] = 5'b0;
      end
    3'b001:
      begin
        // Reg ln0_rx_snap
        rd_ack_d0 = rd_req;
        rd_dat_d0 = ln0_rx_snap_i;
      end
    3'b010:
      begin
        // Reg ln1_rx_snap
        rd_ack_d0 = rd_req;
        rd_dat_d0 = ln1_rx_snap_i;
      end
    3'b011:
      begin
        // Reg ctrl
        rd_ack_d0 = rd_req;
        rd_dat_d0[0] = ctrl_tx_mode_reg;
        rd_dat_d0[31:1] = 31'b0;
      end
    3'b100:
      begin
        // Reg tx_pattern
        rd_ack_d0 = rd_req;
        rd_dat_d0 = tx_pattern_reg;
      end
    default:
      rd_ack_d0 = rd_req;
    endcase
  end
endmodule
